sudo: required 
services:
  - docker

before_install:
  - docker build -t ysergey/docker-react -f Dockerfile.dev . 

script:
  - travis_wait 30 script.sh
  - docker run ysergey/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-743043832396"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"